### ISSUE TITLE
xml:lang will change to  'lang' only

### ISSUE THREAD

**Issue by nrsdnitin** [rquadling/lalit#10]
with xmlToArray, 

if i have attributes like
 
`<Description xml:lang="en-GB" /> Test  </Description>`

it gives me array like 
`
"Description" => array:2 [
              "@value" => "Test"
              "@attributes" => array:1 [
                "lang" => "en-GB"
              ]
            ]
`
and the obvious ArrayToXml output:

`<Description  lang="en-GB" /> Test  </Description>`

**Comment by rquadling** [comment]
Thank you for this. I need to include the namespace. Certainly a bug.

**Comment by dottwatson** [comment]
on line 161 of XML2Array.php change
`$a[$attrName] = $attrNode->value;`
in
`$a[$attrNode->nodeName] = $attrNode->value;`

**Comment by rquadling** [comment]
Thank you @dottwatson.
