### ISSUE TITLE
clean input array before using createXML() ?

### ISSUE THREAD

**Issue by gordielachance** [rquadling/lalit#12]
Hi, 
I'm converting jsons to XML using your class but I often get errors like

> Uncaught Exception: [Array2XML] Illegal character in tag name. tag: $schema in node: root

Is there a way to clean the keys recursively in the array before calling createXML() so that this error is not fired ?  Thanks.

**Comment by gordielachance** [comment]
I found out [this one](https://stackoverflow.com/a/20563452/782013) (need some adaptations), maybe it would be interesting to integrate this in your class, as an option ?

**Comment by rquadling** [comment]
The issue would be that there would be no data available to return the XML to the original array.

So, if you have an invalid key, and this is made valid in some way, the result of XML2Array would not produce the same value.

Of course, adding some meta data to the output of XML2Array could be used, but this could explode the size of the data significantly.

I think is better to understand XML and make sure that the data being produced is consistent with it.

But, if you create a pull request, I'll certainly consider it.

Maybe a separate project to help coerce data into a format suitable for Array2Xml.
