### ISSUE TITLE
[Array2XML] Illegal character in tag name. tag: 7186 in node: root

### ISSUE THREAD

**Issue by gordielachance** [rquadling/lalit#13]
Hi !
Is the error fired because this is a numeric key ?
Shouldn't it be supported ?

**Comment by rquadling** [comment]
Can you show me the data that is generating this issue please.

**Comment by gordielachance** [comment]
sure : https://pastebin.com/aX8FGkPv

**Comment by rquadling** [comment]
Thank you for the example.

First point I'd like to make is with regard to the XML standard.

> XML elements must follow these naming rules:
> 
> Names can contain letters, numbers, and other characters
> Names cannot start with a number or punctuation character
> Names cannot start with the letters xml (or XML, or Xml, etc)
> Names cannot contain spaces
> Any name can be used, no words are reserved.

[W3C Schools](https://www.w3schools.com/xml/xml_elements.asp) and [Official specification](https://www.w3.org/TR/REC-xml/#dt-name)

There would need to be some pre-processing (before calling `Array2XML::createXML()`) done on the array to allow it to be mapped to XML.

If you wanted to be able to reverse the process (i.e. take the XML and create an array), the array would also need some post-processing (after calling `XML2Array::createArray()`) to deal with this.

It would not be possible to do this automatically within this library, for all content as there is no way of knowing if the key, is an original key or a processed key.

For example:

Say you add the text `KEY_` to the beginning of all numeric keys, then the key is now `KEY_7186`. When the XML is converted back to an array, the key is still `KEY_7186` and there would be no easy way to know if this is expected to be the number `7186` or an actual key of `KEY_7186`.

The only real option is for you to control the data and create your own convention, such as any key that is prefixed as `KEY_` and is followed by a number is expected to be just the number.

That way you can pre- and post- process the data to fit accordingly.

**Comment by gordielachance** [comment]
Ok, thanks for your help!

**Comment by gordielachance** [comment]
Still, this is a problem.
Let's say I rename my keys to `key_0`, `key_1`,...
Your code will be able to generate an XML, but it will look like

    <tracks>
        <key_0>...</key_0>
        <key_1>...</key_1>
        <key_2>...</key_2>
    </tracks>

While I would like to have them in a "better" XML formatting, let's say by renaming those keys with the arbitrary word 'item'.

    <tracks>
        <item>...</item>
        <item>...</item>
        <item>...</item>
    </tracks>

The problem is that, if parse my array to rename its keys to 'item' before running arrat2xml, i'll have... only one single key.  I can't give them an identical value.
So in a way or another, I think your code should handle this, no ?

**Comment by rquadling** [comment]
Here's a unit test covering all your requirements.
```php
<?php

namespace LaLit;

use PHPUnit\Framework\TestCase;

/**
 * Class Question013Test.
 */
class Question013Test extends TestCase
{
    /**
     * @param array $array
     * @param string $xml
     *
     * @dataProvider provide013Data
     */
    public function testX2A(array $array, string $xml)
    {
        $this->assertEquals($array, XML2Array::createArray($xml));
    }

    /**
     * @param array $array
     * @param string $xml
     *
     * @dataProvider provide013Data
     */
    public function testA2X(array $array, string $xml)
    {
        $this->assertEquals($xml, Array2XML::createXML('tracks', $array['tracks'])->saveXML());
    }

    public function provide013Data()
    {
        return
            [
                [
                    [
                        'tracks' => [
                            'key_0' => 'zero',
                            'key_1' => 'one',
                            'key_2' => 'two',
                        ],
                    ],
                    <<< 'END_XML'
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<tracks>
  <key_0>zero</key_0>
  <key_1>one</key_1>
  <key_2>two</key_2>
</tracks>

END_XML,
                ],
                [
                    [
                        'tracks' => [
                            'item' => [
                                'zero',
                                'one',
                                'two',
                            ],
                        ],
                    ],
                    <<< 'END_XML'
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<tracks>
  <item>zero</item>
  <item>one</item>
  <item>two</item>
</tracks>

END_XML,
                ],
            ];
    }
}
```

```
$ phpunit tests/bugs/Question013Test.php  --debug
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.33
Configuration: /Users/richardquadling/dt/masters/GitHub/DigiTickets/lalit/phpunit.xml

Test 'LaLit\Question013Test::testX2A with data set #0 (array(array('zero', 'one', 'two')), '<?xml version="1.0" encoding=...cks>\n')' started
Test 'LaLit\Question013Test::testX2A with data set #0 (array(array('zero', 'one', 'two')), '<?xml version="1.0" encoding=...cks>\n')' ended
Test 'LaLit\Question013Test::testX2A with data set #1 (array(array(array('zero', 'one', 'two'))), '<?xml version="1.0" encoding=...cks>\n')' started
Test 'LaLit\Question013Test::testX2A with data set #1 (array(array(array('zero', 'one', 'two'))), '<?xml version="1.0" encoding=...cks>\n')' ended
Test 'LaLit\Question013Test::testA2X with data set #0 (array(array('zero', 'one', 'two')), '<?xml version="1.0" encoding=...cks>\n')' started
Test 'LaLit\Question013Test::testA2X with data set #0 (array(array('zero', 'one', 'two')), '<?xml version="1.0" encoding=...cks>\n')' ended
Test 'LaLit\Question013Test::testA2X with data set #1 (array(array(array('zero', 'one', 'two'))), '<?xml version="1.0" encoding=...cks>\n')' started
Test 'LaLit\Question013Test::testA2X with data set #1 (array(array(array('zero', 'one', 'two'))), '<?xml version="1.0" encoding=...cks>\n')' ended


Time: 30 ms, Memory: 2.00MB

OK (4 tests, 4 assertions)
```

**Comment by gordielachance** [comment]
Hi @rquadling , thanks a lot for your answer.
But I don't get it.  Where is the _assertEquals()_ function defined ?

What I need is to convert a JSON object to an XML.
Here's an [example of input](https://pastebin.com/5AVBgTYP).

In this example, there are numeric keys for 

- lovedtracks > track, 
- lovedtracks > track images

But my input can be any json - I can't rely on a recurrent structure or key names.

What I have for now is

    $json = '...';
    $array = json_decode($json, true);
    $array = clean_array_for_xml($array);

    try{
        $dom = Array2XML::createXML('root', $array);
        $xml = $dom->saveXML($dom);
    }catch(Exception $e){
        return new WP_Error( 'Array2XML', sprintf(__('XML2Array Error [%s] : %s','wpsstmapi'),$e->getCode(),$e->getMessage()) );
    }

    /*
    XML needs properly formatted keys - recursively rename keys if needed
    */
    
    function clean_array_for_xml(&$arr){
        
        //keys: sanitize strings
        $arr = array_combine(
            array_map(
                function ($key) {
                    $key = sanitize_title($key); //this is a Wordpress function that removes all special characters
                    return $key;
                },
                array_keys($arr)
            ),
            array_values($arr)
        );

        foreach ($arr as $key => $val) {
            if (is_array($val)) {
                clean_array_for_xml($arr[$key]);
            }
        }
        
        return $arr;
    }

It would be awesome if I could have a properly formatted XML for this.

Thanks again !

**Comment by gordielachance** [comment]
up ?

**Comment by rquadling** [comment]
The code I've provided is a PHPUnit test demonstrating the library's usage and how to encode the array to produce a valid XML file.

If you need to pre-process the array before feeding it to Array2XML, then that is upto you. The issue you are facing is a restriction of XML.

Converting a JSON string to an array can be done using `json_decode($string, true)`.

After that, you need to iterate the array, replacing any numeric keys with something suitably formatted for XML to allow.

What I can recommend is manually create the XML for this JSON string and then convert the XML using XML2Array to see how it should be formatted.

Then, you can coerce your original array to match the format required.

This pattern would work well for any JSON -> array -> XML.

**Comment by gordielachance** [comment]
Ok, I think I get it.
What I need is to rename my numeric keys to a unique key like 'item' or 'data', and not 'item_0', 'item_1', .... :)
Thanks for your help.

**Comment by gordielachance** [comment]
...well, no, it doesn't work, it gives an array with a single 'data' key :/

**Comment by rquadling** [comment]
By far the most simplest way to deal with this is to manually make the XML you want first.
Maybe not with all the details.
But start with an understanding that LaLit is working with XML and no matter what you want, you will not be able to use LaLit, SimpleXML, DOMDocument, or any other XML tooling to break the standards of XML.

So. Having now got your XML, convert it to an array. And then convert it to JSON. You'll have your perfect form.

NOW you can map your much larger set of data to this form and happily convert it to XML.

**Comment by rquadling** [comment]
I also think you have missed the unit test code I created demonstrating the formats I think you are asking for:
```
<tracks>
    <item>...</item>
    <item>...</item>
    <item>...</item>
</tracks>
```
and
```
[
 'tracks' => [
  'item' => [
   'zero',
   'one',
   'two',
  ],
 ],
]
```

are the forms I think you need to be using.

**Comment by gordielachance** [comment]
> So. Having now got your XML, convert it to an array. And then convert it to JSON. You'll have your perfect form.

(What I need is the opposite: convert an array to XML)

> But start with an understanding that LaLit is working with XML and no matter what you want, you will not be able to use LaLit, SimpleXML, DOMDocument, or any other XML tooling to break the standards of XML.

Yeah, I got that. I have a function to pre-process my array before using Array2XML, so I can clean my input.

> I also think you have missed the unit test code I created demonstrating the formats I think you are asking for:

```
  'item' => [
   'zero',
   'one',
   'two',
  ],
```

Thing is, using that form of arrays throws an _Illegal character in tag name_ error since it is an indexed (not associative) array ! (my original question).

Sorry if there is something I don't get, I'm french speaking and maybe I miss something of your explanation ?

**Comment by rquadling** [comment]
To understand the required format of your array, you need to start with a valid XML that you would expect, convert that XML to an array. You will now have the model for your array. You create the XML by hand to make sure it is valid, so you can then convert it to an array and see the shape of the array you then need to be making from your pre-processing.

Array2XML -> XML2Array -> Array2XML -> ...

The whole point of these tools is that they can be repeatedly used and there should be no data loss.

So, whilst your end goal is to convert an array to XML, knowing the expected shape of the XML, and converting that to an array, will demonstrate what the array needs to look like.

As it stands, there's no need to keep this issue open as there limiting factor is the rules by which XML operates.

I've hopefully described a suitable path for you to take.
