### ISSUE TITLE
Array2XML is not handling invalid characters in node values

### ISSUE THREAD

**Issue by JanisE** [rquadling/lalit#17]
If you do this:

`print_r(\LaLit\XML2Array::createArray(\LaLit\Array2XML::createXML('myxml', ['ttt' => 'oo  o'])->saveXML()));`

you'll get a PHP fatal error "Error parsing the XML string" even though the XML string is prepared by `\LaLit\Array2XML` itself.

The reason is that a PHP string may contain characters that are invalid in XML, see https://www.w3.org/TR/xml/#NT-Char
For example, characters x00-x09 are invalid, x02 is being used in the code example above.

Getting such characters into data is easy enough, e.g., it may happen when copying content from a PDF viewer.

Seeing how there already is exception `[Array2XML] Illegal character in attribute name.` possible, there should also be an exception for illegal characters in node values.

**Comment by rquadling** [comment]
Thanks for this. Apologies for the delay in handling this.

**Comment by rquadling** [comment]
Hopefully all fixed in v3.4.0
