### ISSUE TITLE
Some characters are modified/encoded in XML output

### ISSUE THREAD

**Issue by diamondavocado** [rquadling/lalit#18]
I'm fetching some data from a MySQL table via PDO, then using Array2XML to write that data to an XML file. The encoding of my MySQL database/table/column is `utf8mb4`.

My problem is that some data seems to get modified by Array2XML as it's being converted to XML.

For example, in the database I have a carriage return character which appears in the XML output as `&#13;`, the HTML entity encoded version of a carriage return.

Illustrative example:

```php
<?php

// print_r($array);
[content] => "Here I have a
carriage return"

// echo $xml->saveXML();
<content>Here I have a &#13;carriage return</content>
```

**Comment by rquadling** [comment]
Thanks for the example. And VERY sorry for the delay in responding.

**Comment by rquadling** [comment]
`\r` => `&#13` is XML for you. Only newlines (`\n`) are allowed.

I refer you to https://stackoverflow.com/questions/2265966/xml-carriage-return-encoding for a more thorough explanation.
