### ISSUE TITLE
CreateXML $node_name

### ISSUE THREAD

**Issue by blagi** [rquadling/lalit#20]
I'd like to create XML from array and have a few questions about array2XML features.
1.
In my case XML has to star with this node:
```
<dpi:DPI_OECD xmlns:dpi="urn:oecd:ties:dpi:v1" xmlns:stf="urn:oecd:ties:dpistf:v1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0"
    xsi:schemaLocation="urn:oecd:ties:dpi:v1 ../XSD/DPIXML_v1.0.xsd">
    
```
or with SOAP signature:
`<soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope">
`
But looks like $node_name parameter of createXML method cannot be used to create such and XML. 
How to solve this?

2.
I have a multiple nodes of same name. How to handle them in an array?

3.
Is it possible to create partial document with Array2XML and then embed it into main XML document as some child?

**Comment by rquadling** [comment]
Hi.

Thank you for finding an issue in the XML2Array code - when reading an XML document with multiple namespaces declarations, the namespaces are not picked up and held in the array.

But, if they _were_ present in the root nodes `@attributes` array, they would be in the resultant XML output for Array2XML.

Root node namespace declarations are not much more than ...
```php
$array = [
    'root_node_name' => [
        '@attributes' = [
            'xmlns:abc' => 'something relevant',
        ],
    ],
];
```

I'm just releasing an upgrade for the additional namespaces.

And apologies for taking so long. This repo really doesn't get a lot of activity!

**Comment by blagi** [comment]
> Hi.
> 
> Thank you for finding an issue in the XML2Array code - when reading an XML document with multiple namespaces declarations, the namespaces are not picked up and held in the array.
> 
> But, if they _were_ present in the root nodes `@attributes` array, they would be in the resultant XML output for Array2XML.
> 
> Root node namespace declarations are not much more than ...
> 
> ```
> $array = [
>     'root_node_name' => [
>         '@attributes' = [
>             'xmlns:abc' => 'something relevant',
>         ],
>     ],
> ];
> ```
> 
> I'm just releasing an upgrade for the additional namespaces.
> 
> And apologies for taking so long. This repo really doesn't get a lot of activity!

Thanks! That's just great. 

But I did solved my XMLcreating task  in a primitive way by manually constructing XML file. :(
