### ISSUE TITLE
Problem with @value elements ...

### ISSUE THREAD

**Issue by AlgyTaylor** [rquadling/lalit#3]
Heya,

Awesome work by both the original author & yourself :+1: 

Anyway,  I've found what appears to be a bug.  When parsing this

```
array (
    "hpo" => array (
        "HP_0012759" => array (
            "term" => "Neurodevelopmental abnormality",
            "@attributes" => array (
                "present" => "na"
            ),
            "onset" => array (
                "@attributes" => array (
                    "units" => "years"
                ),
                "@value" => NULL
            )
        )
    )
)
```

I get an exception `Message: [Array2XML] Illegal character in tag name. tag: @value in node: onset`

Cheers,
Algy

**Comment by rquadling** [comment]
Can you supply the XML that you used to build this please?

**Comment by AlgyTaylor** [comment]
Heya, that was the value I'd entered in to Array2XML - I didn't use XML2Array beforehand.

**Comment by rquadling** [comment]
OK. Change `NULL` to `''`. Does it work?

**Comment by rquadling** [comment]
Aha! I see the issue.

`if (isset($arr['@value'])) {`

When `$arr['@value'] === null` this test fails.

Should work with `array_key_exists`.

**Comment by rquadling** [comment]
Fix on the way.

**Comment by rquadling** [comment]
Done.
