### ISSUE TITLE
PHP7 specific issue in array2xml

### ISSUE THREAD

**Issue by vinpel** [rquadling/lalit#5]
Hello, i have found a very strange bug.

in some case the "is_numeric(key($value)" return null in php 7, but not php 5.6, ending up with an error : 
```bash
[Array2XML] Illegal character in tag name. tag: 0 in node: data
```
The used array is (with print_r result) : 
```code
Array
(
    [element] => Array
        (
            [0] => Array
                (
                    [trigger_table] => messages
                    [action] => insert
                    [unicite] => 100001##ico-CpswP0E3EJPLAule1N5hc68TiYm_np3LMxmdk-O6LAe4P_vqcK
                    [data] => Array
                        (
                            [0] => Array
                                (
                                    [icone] => ico-CpswP0E3EJPLAule1N5hc68TiYm_np3LMxmdk-O6LAe4P_vqcK
                                    [userid] => 100001
                                    [sujet] => sujet-SOScngEPXzcQ_MBK6dMi2Fco-GbtDGewd1lRZxajkg4Jcc1jmg
                                )

                        )

                )

            [1] => Array
                (
                    [trigger_table] => messages
                    [action] => insert
                    [unicite] => 100001##ico-Y2QIAITIeorcfTONGyFfWapulT4E5B73qwCMKiEvRaAEnBOV5A
                    [data] => Array
                        (
                            [0] => Array
                                (
                                    [icone] => ico-Y2QIAITIeorcfTONGyFfWapulT4E5B73qwCMKiEvRaAEnBOV5A
                                    [userid] => 100001
                                    [sujet] => sujet-NLt1uZgkKx-7_FNqCgx7UW9myPPxKDqRJeWQTjuQ6zNtR4kA36
                                )

                        )

                )

        )

)
```

I can correct the error 2 way :
Bad way :
```php
$array_good=json_decode(json_encode($array),true);
```

Good but i don't know why way :
```php
          throw new Exception('[Array2XML] Illegal character in tag name. tag: '.$key.' in node: '.$node_name);
        }
        if (is_array($value) 
          && (is_null(key($value)) || is_numeric(key($value)))) {
          // MORE THAN ONE NODE OF ITS KIND;
          // if the new array is numeric index, means it is array of nodes of the same kind
          // it should follow the parent key name
          foreach ($value as $k => $v) {
            $node->appendChild(self::convert($key, $v));
          }
```
maybe the array i generate is wrong someway, but var_dump the before / after json result as EXACTLY the same string, so i don't know how to see the difference between the 2 array

In the php7 change http://php.net/manual/en/migration70.incompatible.php
```
Changes to foreach ¶

Minor changes have been made to the behaviour of the foreach control structure, primarily around the handling of the internal array pointer and modification of the array being iterated over.

foreach no longer changes the internal array pointer
```

**Comment by rquadling** [comment]
The array data needs to be split into `@value` and `@attributes` as XML has both.

As a test, manually create the XML you would like to have as output and then run it through XML2Array. That will show you what your array should look like.

https://raw.githubusercontent.com/digitickets/lalit/master/tests/files/testData.inc (it's big) contains the test XML and PHP Arrays.

As an example, starting with:
```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<root attribute4="\'&lt;important&gt;\'">
  <collection attribute1="">
    <node attribute4="\'&lt;important&gt;\'"></node>
    <node attribute4="\'&lt;important&gt;\'"></node>
  </collection>
</root>
```
You get a PHP array of:
```php
    array (
      'root' => 
      array (
        'collection' => 
        array (
          'node' => 
          array (
            0 => 
            array (
              '@value' => NULL,
              '@attributes' => 
              array (
                'attribute4' => '\'<important>\'',
              ),
            ),
            1 => 
            array (
              '@value' => NULL,
              '@attributes' => 
              array (
                'attribute4' => '\'<important>\'',
              ),
            ),
          ),
          '@attributes' => 
          array (
            'attribute1' => '',
          ),
        ),
        '@attributes' => 
        array (
          'attribute4' => '\'<important>\'',
        ),
      ),
    );
```

**Comment by vinpel** [comment]
it's specific with php7.

i've found the function who cause the problem :

```php
  function array2Utf8($array){
    array_walk_recursive($array, function(&$item, $key){
      if(!mb_detect_encoding($item, 'utf-8', true)){
        $item = utf8_encode($item);
      }
    });
    return $array;
  }
```

if i transform the function like this it still trigger the exception :
```php
  function array2Utf8($array){
    array_walk_recursive($array, function(&$item, $key){
     });
    return $array;
  }
```
and this don't trigger the exception :
```php
  function array2Utf8($array){
      return $array;
  }
```
really strange for **array_walk_recursive**  i don't find difference php7 <>php5 and normally the 2nd function don't transform the array ..

**Comment by rquadling** [comment]
Can you generate an XML file or PHP array that will cause this issue.

Please note that the array you send to Array2XML is not a general purpose PHP array. It is one with a specific structure.

I've added PHP 5.6 to the travis build and it is passing all tests as expected.

https://travis-ci.org/digitickets/lalit/jobs/217179295#L191

Without a test case, I cannot see what's wrong. Your PHP array is not correctly structured for Array2XML. If you can produce an XML that fails, then I can certainly look into this further.

With regard to the specific issue though, the incorrect structure of your array is telling Array2XML that a numeric key is the name of the tag. As XML tags cannot start with a number, this is an invalid entry.

In addition, you are declaring the root of your tree as 'element', so there is no node to repeat, hence the key being attempted to be treated as a node name.

So, manually create the XML file you expect (at least a shortened version), use XML2Array on it to see what your PHP array should look like and then extend from there.
